Repository TEAM-JJINS/cs-algo, pull requests merged in 2025-08, with the labels that each got.

#172 [Chore] NCP SourceCommit 활용을 위한 Workflow 작성 #162
  .github/workflows/push-to-sourcecommit.yml
Labels: enhancement

#174 [Chore] sourcecommit push 시 인증방식 수정 #161
  .github/workflows/push-to-sourcecommit.yml
Labels: bug

#175 [Chore] NCR 기반 CI/CD 파이프라인 구축 및 NKS 클러스터 배포
  .github/workflows/deploy-nks-terraform.yml
  .github/workflows/deploy.yml.disabled
  csalgo-iac/main.tf
  csalgo-iac/modules/mysql/main.tf
  csalgo-iac/modules/server/main.tf
  csalgo-iac/modules/server/variables.tf
  csalgo-iac/modules/web/main.tf
  csalgo-iac/provider.tf
  csalgo-iac/variables.tf
  kubeconfig.b64
Labels: enhancement

#178 [Feature] 정적 리소스 호스팅 NCP Object Storage로 이전 #177
  csalgo-common/src/main/java/kr/co/csalgo/common/util/ImageUrlProvider.java
  csalgo-common/src/main/java/kr/co/csalgo/common/util/MailTemplate.java
  csalgo-server/src/main/resources/application.yml
  csalgo-web/src/main/resources/application.yml
  csalgo-web/src/main/resources/templates/fragments/common/navbar.html
Labels: enhancement

#182 [Feature] Jwt 인증 필터 구현을 통한 ROLE 기반 접근 제어 및 @PreAuthorize 적용 #135
  csalgo-common/src/main/java/kr/co/csalgo/common/exception/ErrorCode.java
  csalgo-infrastructure/src/main/java/kr/co/csalgo/infrastructure/security/CustomAccessDeniedHandler.java
  csalgo-infrastructure/src/main/java/kr/co/csalgo/infrastructure/security/CustomAuthenticationEntryPoint.java
  csalgo-infrastructure/src/main/java/kr/co/csalgo/infrastructure/security/JwtAuthenticationFilter.java
  csalgo-infrastructure/src/main/java/kr/co/csalgo/infrastructure/security/JwtProvider.java
  csalgo-server/build.gradle
  csalgo-server/src/main/java/kr/co/csalgo/server/config/SecurityConfig.java
  csalgo-server/src/main/java/kr/co/csalgo/server/question/QuestionController.java
  csalgo-server/src/main/java/kr/co/csalgo/server/user/UserController.java
  csalgo-server/src/test/java/kr/co/csalgo/server/question/QuestionControllerTest.java
  csalgo-server/src/test/java/kr/co/csalgo/server/user/UserControllerTest.java
Labels: ✨ feature, 🧑🏻‍💼 domain: admin, ⚙️ backend

#185 [Docs] 프로젝트 README 구조 개편 #184
  README.md
Labels: 📄 documentation

#188 [Fix] NKS의 Web Deployment에 jwt_secret 환경변수 추가 #187
  csalgo-iac/main.tf
  csalgo-iac/modules/web/main.tf
  csalgo-iac/modules/web/variables.tf
Labels: 🔄 bug, ☁ iac

#192 [Fix] 리프레시 토큰 재발급 오류 해결 #191
  csalgo-infrastructure/src/main/java/kr/co/csalgo/infrastructure/security/CustomAccessDeniedHandler.java
  csalgo-web/build.gradle
  csalgo-web/src/main/java/kr/co/csalgo/web/admin/client/AdminRestClient.java
  csalgo-web/src/main/java/kr/co/csalgo/web/admin/controller/AdminWebController.java
  csalgo-web/src/main/java/kr/co/csalgo/web/admin/dto/UserDto.java
  csalgo-web/src/main/java/kr/co/csalgo/web/admin/service/AdminService.java
  csalgo-web/src/main/java/kr/co/csalgo/web/common/dto/PagedResponse.java
  csalgo-web/src/main/java/kr/co/csalgo/web/config/SecurityConfig.java
  csalgo-web/src/main/java/kr/co/csalgo/web/security/JwtAuthenticationFilter.java
  csalgo-web/src/main/java/kr/co/csalgo/web/security/JwtValidator.java
  csalgo-web/src/main/resources/static/js/http.js
Labels: 🔄 bug, 🧑🏻‍💼 domain: admin, 🎨 frontend

#198 [Feature] 사용자 권한 변경 API 구현 #145
  csalgo-application/src/main/java/kr/co/csalgo/application/admin/dto/UpdateRoleDto.java
  csalgo-application/src/main/java/kr/co/csalgo/application/admin/usecase/AdminLoginUseCase.java
  csalgo-application/src/main/java/kr/co/csalgo/application/admin/usecase/UpdateUseCase.java
  csalgo-application/src/test/java/kr/co/csalgo/application/admin/usecase/AdminLoginUseCaseTest.java
  csalgo-application/src/test/java/kr/co/csalgo/application/admin/usecase/UpdateUseCaseTest.java
  csalgo-common/src/main/java/kr/co/csalgo/common/exception/ErrorCode.java
  csalgo-common/src/main/java/kr/co/csalgo/common/message/MessageCode.java
  csalgo-domain/src/main/java/kr/co/csalgo/domain/user/service/UserService.java
  csalgo-domain/src/test/java/kr/co/csalgo/domain/service/UserServiceTest.java
  csalgo-server/build.gradle
  csalgo-server/src/main/java/kr/co/csalgo/server/config/SecurityConfig.java
  csalgo-server/src/main/java/kr/co/csalgo/server/user/UserController.java
  csalgo-server/src/test/java/kr/co/csalgo/server/user/UserControllerTest.java
Labels: ✨ feature, 🧑🏻‍💼 domain: admin, ⚙️ backend

#200 [Feature] 어드민 페이지 문제 삭제 기능 연동 #197
  csalgo-web/src/main/java/kr/co/csalgo/web/admin/client/AdminRestClient.java
  csalgo-web/src/main/java/kr/co/csalgo/web/admin/controller/AdminWebController.java
  csalgo-web/src/main/java/kr/co/csalgo/web/admin/service/AdminService.java
  csalgo-web/src/main/java/kr/co/csalgo/web/common/dto/MessageResponseDto.java
  csalgo-web/src/main/resources/static/css/style.css
  csalgo-web/src/main/resources/static/js/question-delete.js
  csalgo-web/src/main/resources/templates/admin/dashboard/questions.html
Labels: ✨ feature, 🧑🏻‍💼 domain: admin, 🎨 frontend

#202 [Feature] 어드민 페이지 문제 상세 조회 및 수정 기능 구현 #132, #196
  csalgo-application/src/main/java/kr/co/csalgo/application/problem/usecase/UpdateQuestionUseCase.java
  csalgo-application/src/test/java/kr/co/csalgo/application/problem/usecase/UpdateQuestionUseCaseTest.java
  csalgo-server/src/main/java/kr/co/csalgo/server/question/QuestionController.java
  csalgo-server/src/test/java/kr/co/csalgo/server/question/QuestionControllerTest.java
  csalgo-web/src/main/java/kr/co/csalgo/web/admin/client/AdminRestClient.java
  csalgo-web/src/main/java/kr/co/csalgo/web/admin/controller/AdminWebController.java
  csalgo-web/src/main/java/kr/co/csalgo/web/admin/dto/QuestonDto.java
  csalgo-web/src/main/java/kr/co/csalgo/web/admin/service/AdminService.java
  csalgo-web/src/main/resources/static/js/question-delete.js
  csalgo-web/src/main/resources/static/js/question-update.js
  csalgo-web/src/main/resources/templates/admin/dashboard/question.html
  csalgo-web/src/main/resources/templates/admin/dashboard/questions.html
Labels: ✨ feature, 🧑🏻‍💼 domain: admin, 🎨 frontend
